inputConfiguration = {... % inputFolder, configuration, timepoints, specimens, cameras, channels, outputFolderLabel
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '14-05-21 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:531,  0,   0:1, 0:1, '14-05-21';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '14-08-13 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:285,  0,   0:1, 0,   '14-08-13';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '14-08-13 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections',          '.corrected.shifted', 0:285,  0,   0:1, 0,   '14-08-13.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '14-10-09 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections.200202',           '.corrected',         0:312,  0,   0:1, 0,   '14-10-09';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '14-10-09 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections.200202',   '.corrected.shifted', 0:312,  0,   0:1, 0,   '14-10-09.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-01-30 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections.140900',           '.corrected',         0:450,  0:1, 0:1, 0,   '15-01-30';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-04-03 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:499,  0,   0:1, 0,   '15-04-03';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-04-03 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections',          '.corrected.shifted', 0:499,  0,   0:1, 0,   '15-04-03.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-04-17 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections.SPM0',             '.corrected',         0:1192, 0,   0:1, 0,   '15-04-17';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-04-17 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections.SPM1',             '.corrected',         0:1192, 1,   0:1, 0,   '15-04-17';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-08-10 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:370,  0:1, 0:1, 0,   '15-08-10';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-09-30 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:552,  0:1, 0:1, 0,   '15-09-30';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-10-26 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections.180901',           '.corrected',         0:270,  0,   0:1, 0,   '15-10-26';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-10-26 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections.180901',   '.corrected.shifted', 0:270,  0,   0:1, 0,   '15-10-26.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-10-26 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections.Combined',         '.corrected',         0:649,  0,   0:1, 0,   '15-10-26.Combined';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-10-26 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections.Combined', '.corrected.shifted', 0:649,  0,   0:1, 0,   '15-10-26.Combined.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-11-04 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections.165657',           '.corrected',         0:350,  0,   0:1, 0,   '15-11-04';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-11-04 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections.165657',   '.corrected.shifted', 0:350,  0,   0:1, 0,   '15-11-04.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-11-14 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:350,  0,   0:1, 0,   '15-11-14';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-11-14 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections',          '.corrected.shifted', 0:350,  0,   0:1, 0,   '15-11-14.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-11-17 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:307,  0,   0:1, 0:1, '15-11-17';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-11-17 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections',          '.corrected.shifted', 0:307,  0,   0:1, 0:1, '15-11-17.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-12-05 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:500,  0,   0:1, 0,   '15-12-05';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '15-12-05 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections',          '.corrected.shifted', 0:500,  0,   0:1, 0,   '15-12-05.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-01-12 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:324,  0,   0:1, 0,   '16-01-12';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-01-12 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections',          '.corrected.shifted', 0:324,  0,   0:1, 0,   '16-01-12.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-01-13 Temporal Registration Assessment' filesep 'TimeFused.Wavelet.Projections',                    '',                   0:322,  0,   0:1, 0,   '16-01-13';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-01-13 Temporal Registration Assessment' filesep 'TimeFused.Wavelet.Shifted.Projections',            '.shifted',           0:322,  0,   0:1, 0,   '16-01-13.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-03-15 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:291,  0,   0:1, 0:1, '16-03-15';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-03-15 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections',          '.corrected.shifted', 0:291,  0,   0:1, 0:1, '16-03-15.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-03-26 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:368,  0,   0:1, 0,   '16-03-26';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-03-26 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections',          '.corrected.shifted', 0:368,  0,   0:1, 0,   '16-03-26.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-03-28 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:600,  0,   0:1, 0,   '16-03-28';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-03-28 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections',          '.corrected.shifted', 0:600,  0,   0:1, 0,   '16-03-28.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-06-01 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:500,  0,   0:1, 0:1, '16-06-01';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-06-01 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections',          '.corrected.shifted', 0:500,  0,   0:1, 0:1, '16-06-01.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-06-14 Temporal Registration Assessment' filesep 'TimeFused.Geometric.Projections',                  '',                   0:258,  0,   0:1, 0:1, '16-06-14';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-06-14 Temporal Registration Assessment' filesep 'TimeFused.Geometric.Shifted.Projections',          '.shifted',           0:258,  0,   0:1, 0:1, '16-06-14.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-06-16 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:300,  0,   0:1, 0,   '16-06-16';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-06-16 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections',          '.corrected.shifted', 0:300,  0,   0:1, 0:1, '16-06-16.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-06-16 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Master.Shifted.Projections',   '.corrected.shifted', 0:300,  0,   0:1, 0:1, '16-06-16.Master.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-07-16 Temporal Registration Assessment' filesep 'TimeFused.Blending.Projections',                   '',                   0:271,  0,   0:1, 0:1, '16-07-16.Blending';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-07-16 Temporal Registration Assessment' filesep 'TimeFused.Blending.Shifted.Projections',           '.shifted',           0:271,  0,   0:1, 0:1, '16-07-16.Blending.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-07-16 Temporal Registration Assessment' filesep 'TimeFused.Wavelet.Projections',                    '',                   0:271,  0,   0:1, 0:1, '16-07-16.Wavelet';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-07-16 Temporal Registration Assessment' filesep 'TimeFused.Wavelet.Shifted.Projections',            '.shifted',           0:271,  0,   0:1, 0:1, '16-07-16.Wavelet.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-07-23 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:265,  0,   0:1, 0:1, '16-07-23';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-07-23 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections',          '.corrected.shifted', 0:265,  0,   0:1, 0:1, '16-07-23.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-07-26 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:257,  0,   0:1, 0:1, '16-07-26';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-07-26 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections',          '.corrected.shifted', 0:257,  0,   0:1, 0:1, '16-07-26.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-07-29 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:600,  0,   0:1, 0,   '16-07-29';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-07-29 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Shifted.Projections',          '.corrected.shifted', 0:600,  0,   0:1, 0,   '16-07-29.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-10-13 Temporal Registration Assessment' filesep 'TimeFused.Corrected.Projections',                  '.corrected',         0:215,  0,   0:1, 0:1, '16-10-13';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-12-15 Temporal Registration Assessment' filesep 'TimeFused.Geometric.Projections',                  '',                   0:192,  0,   0:1, 0:1, '16-12-15.Blending';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-12-15 Temporal Registration Assessment' filesep 'TimeFused.Geometric.Shifted.Projections',          '.shifted',           0:192,  0,   0:1, 0:1, '16-12-15.Blending.Shifted';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-12-15 Temporal Registration Assessment' filesep 'TimeFused.Wavelet.Projections',                    '',                   0:192,  0,   0:1, 0:1, '16-12-15.Wavelet';...
    'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-12-15 Temporal Registration Assessment' filesep 'TimeFused.Wavelet.Shifted.Projections',            '.shifted',           0:192,  0,   0:1, 0:1, '16-12-15.Wavelet.Shifted';...
    ...
    % 'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-03-28 Temporal Registration Assessment' filesep 'TimeFused.Projections',                          '',                   0:600,  0,   0:1, 0,   '16-03-28';...
    % 'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep '16-06-16 Temporal Registration Assessment' filesep 'TimeFusedWavelet.Projections',                   '',                   0:300,  0,   0:1, 0:1, '16-06-16';...
    };

outputRoot = 'E:' filesep 'Mouse Development' filesep 'Time-Lapse Registration' filesep 'Assembled Projections';

globalSearch = 1;

%% main loop

disp(' ');

if exist(outputRoot, 'dir') ~= 7
    mkdir(outputRoot);
end;

for i = 1:size(inputConfiguration, 1)
    for s = inputConfiguration{i, 4}
        for c = inputConfiguration{i, 6}
            
            % if strcmp(inputConfiguration{i, 2}, '.corrected') || strcmp(inputConfiguration{i, 2}, '.corrected.shifted')
            %     xyStackName = [outputRoot filesep '' inputConfiguration{i, 7} '.S' num2str(s) '_C' num2str(c) '_xy.klb'];
            %     xzStackName = [outputRoot filesep '' inputConfiguration{i, 7} '.S' num2str(s) '_C' num2str(c) '_xz.klb'];
            %     yzStackName = [outputRoot filesep '' inputConfiguration{i, 7} '.S' num2str(s) '_C' num2str(c) '_yz.klb'];
            % else
            %     xyStackName = [outputRoot filesep '' inputConfiguration{i, 7} '.S' num2str(s) '_C' num2str(c) '_xy.uncorrected.klb'];
            %     xzStackName = [outputRoot filesep '' inputConfiguration{i, 7} '.S' num2str(s) '_C' num2str(c) '_xz.uncorrected.klb'];
            %     yzStackName = [outputRoot filesep '' inputConfiguration{i, 7} '.S' num2str(s) '_C' num2str(c) '_yz.uncorrected.klb'];
            % end;
            
            xyStackName = [outputRoot filesep '' inputConfiguration{i, 7} '.S' num2str(s) '_C' num2str(c) '_xy.klb'];
            xzStackName = [outputRoot filesep '' inputConfiguration{i, 7} '.S' num2str(s) '_C' num2str(c) '_xz.klb'];
            yzStackName = [outputRoot filesep '' inputConfiguration{i, 7} '.S' num2str(s) '_C' num2str(c) '_yz.klb'];
            
            if exist(xyStackName, 'file') ~= 2 || exist(xzStackName, 'file') ~= 2 || exist(yzStackName, 'file') ~= 2
                
                % if strcmp(inputConfiguration{i, 2}, '.corrected') || strcmp(inputConfiguration{i, 2}, '.corrected.shifted')
                %     disp(['Generating projection stacks ' xyStackName(1:(end-6)) '??.klb']);
                % else
                %     disp(['Generating projection stacks ' xyStackName(1:(end-18)) '??.uncorrected.klb']);
                % end;
                
                disp(['Generating projection stacks ' xyStackName(1:(end-6)) '??.klb']);
                
                if globalSearch
                    for t = fliplr(inputConfiguration{i, 3})
                        xyTestHeader = readKLBheader([inputConfiguration{i, 1} filesep 'SPM' num2str(s, '%.2d') '_TM' num2str(t, '%.6d') ...
                            '_CM' num2str(inputConfiguration{i, 5}(1), '%.2d') '_CM' num2str(inputConfiguration{i, 5}(2), '%.2d') ...
                            '_CHN' num2str(c, '%.2d') '.fusedStack_xyProjection' inputConfiguration{i, 2} '.klb']);
                        xzTestHeader = readKLBheader([inputConfiguration{i, 1} filesep 'SPM' num2str(s, '%.2d') '_TM' num2str(t, '%.6d') ...
                            '_CM' num2str(inputConfiguration{i, 5}(1), '%.2d') '_CM' num2str(inputConfiguration{i, 5}(2), '%.2d') ...
                            '_CHN' num2str(c, '%.2d') '.fusedStack_xzProjection' inputConfiguration{i, 2} '.klb']);
                        
                        if t == inputConfiguration{i, 3}(end)
                            xSize = xyTestHeader.xyzct(1);
                            ySize = xyTestHeader.xyzct(2);
                            zSize = xzTestHeader.xyzct(2);
                        else
                            xSize = max(xyTestHeader.xyzct(1), xSize);
                            ySize = max(xyTestHeader.xyzct(2), ySize);
                            zSize = max(xzTestHeader.xyzct(2), zSize);
                        end;
                        
                        xyStack = zeros(xSize, ySize, numel(inputConfiguration{i, 3}), 'uint16');
                        xzStack = zeros(xSize, zSize, numel(inputConfiguration{i, 3}), 'uint16');
                        yzStack = zeros(ySize, zSize, numel(inputConfiguration{i, 3}), 'uint16');
                    end;
                end;
                
                for t = fliplr(inputConfiguration{i, 3})
                    if t == inputConfiguration{i, 3}(end) && ~globalSearch
                        xyTestFrame = readImage([inputConfiguration{i, 1} filesep 'SPM' num2str(s, '%.2d') '_TM' num2str(t, '%.6d') ...
                            '_CM' num2str(inputConfiguration{i, 5}(1), '%.2d') '_CM' num2str(inputConfiguration{i, 5}(2), '%.2d') ...
                            '_CHN' num2str(c, '%.2d') '.fusedStack_xyProjection' inputConfiguration{i, 2} '.klb']);
                        xzTestFrame = readImage([inputConfiguration{i, 1} filesep 'SPM' num2str(s, '%.2d') '_TM' num2str(t, '%.6d') ...
                            '_CM' num2str(inputConfiguration{i, 5}(1), '%.2d') '_CM' num2str(inputConfiguration{i, 5}(2), '%.2d') ...
                            '_CHN' num2str(c, '%.2d') '.fusedStack_xzProjection' inputConfiguration{i, 2} '.klb']);
                        yzTestFrame = readImage([inputConfiguration{i, 1} filesep 'SPM' num2str(s, '%.2d') '_TM' num2str(t, '%.6d') ...
                            '_CM' num2str(inputConfiguration{i, 5}(1), '%.2d') '_CM' num2str(inputConfiguration{i, 5}(2), '%.2d') ...
                            '_CHN' num2str(c, '%.2d') '.fusedStack_yzProjection' inputConfiguration{i, 2} '.klb']);
                        
                        xSize = size(xyTestFrame, 1);
                        ySize = size(xyTestFrame, 2);
                        zSize = size(xzTestFrame, 2);
                        
                        xyStack = zeros(size(xyTestFrame, 1), size(xyTestFrame, 2), numel(inputConfiguration{i, 3}), 'uint16');
                        xzStack = zeros(size(xzTestFrame, 1), size(xzTestFrame, 2), numel(inputConfiguration{i, 3}), 'uint16');
                        yzStack = zeros(size(yzTestFrame, 1), size(yzTestFrame, 2), numel(inputConfiguration{i, 3}), 'uint16');
                        
                        xyStack(:, :, end) = xyTestFrame;
                        xzStack(:, :, end) = xzTestFrame;
                        yzStack(:, :, end) = yzTestFrame;
                    else
                        tSlot = find(inputConfiguration{i, 3} == t, 1);
                        
                        xyCurrentFrame = readImage([inputConfiguration{i, 1} filesep 'SPM' num2str(s, '%.2d') '_TM' num2str(t, '%.6d') ...
                            '_CM' num2str(inputConfiguration{i, 5}(1), '%.2d') '_CM' num2str(inputConfiguration{i, 5}(2), '%.2d') ...
                            '_CHN' num2str(c, '%.2d') '.fusedStack_xyProjection' inputConfiguration{i, 2} '.klb']);
                        xzCurrentFrame = readImage([inputConfiguration{i, 1} filesep 'SPM' num2str(s, '%.2d') '_TM' num2str(t, '%.6d') ...
                            '_CM' num2str(inputConfiguration{i, 5}(1), '%.2d') '_CM' num2str(inputConfiguration{i, 5}(2), '%.2d') ...
                            '_CHN' num2str(c, '%.2d') '.fusedStack_xzProjection' inputConfiguration{i, 2} '.klb']);
                        yzCurrentFrame = readImage([inputConfiguration{i, 1} filesep 'SPM' num2str(s, '%.2d') '_TM' num2str(t, '%.6d') ...
                            '_CM' num2str(inputConfiguration{i, 5}(1), '%.2d') '_CM' num2str(inputConfiguration{i, 5}(2), '%.2d') ...
                            '_CHN' num2str(c, '%.2d') '.fusedStack_yzProjection' inputConfiguration{i, 2} '.klb']);
                        
                        xzOffset = round((zSize - size(xzCurrentFrame, 2)) / 2) + 1;
                        yzOffset = round((zSize - size(yzCurrentFrame, 2)) / 2) + 1;
                        
                        xyStack(:, :, tSlot) = xyCurrentFrame;
                        xzStack(:, xzOffset:(xzOffset + size(xzCurrentFrame, 2) - 1), tSlot) = xzCurrentFrame;
                        yzStack(:, yzOffset:(yzOffset + size(yzCurrentFrame, 2) - 1), tSlot) = yzCurrentFrame;
                    end;
                end;
                
                writeImage(xyStack, xyStackName);
                writeImage(xzStack, xzStackName);
                writeImage(yzStack, yzStackName);
            end;
        end;
    end;
end;

disp(' ');